BEGIN;

SET CLIENT_ENCODING TO 'UTF-8';

DROP TABLE IF EXISTS "admin", "customer", "product", "cart", "cart_item";

CREATE TABLE "admin" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "role" VARCHAR(1) NOT NULL,
    "email" VARCHAR(80) UNIQUE NOT NULL,
    "lastname" VARCHAR(80) NOT NULL,
    "firstname" VARCHAR(80) NOT NULL,
    "password" VARCHAR(80) NOT NULL,
    "created_date" TIMESTAMP
);

CREATE TABLE "customer" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "email" VARCHAR(80) UNIQUE NOT NULL,
    "lastname" VARCHAR(80),
    "firstname" VARCHAR(80),
    "password" VARCHAR(80) NOT NULL,
    "number" VARCHAR(80),
    "city" VARCHAR(80),
    "address" TEXT,
    "zip_code" VARCHAR(80),
    "phone" VARCHAR(80),
    "created_date" TIMESTAMP
);

CREATE TABLE "product" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" VARCHAR(80) NOT NULL,
    "name" VARCHAR(80) NOT NULL,
    "type" VARCHAR(80) NOT NULL,
    "img_url" VARCHAR(255),
    "price" FLOAT NOT NULL,
    "description" VARCHAR(255) NOT NULL,
    "quantity" INTEGER NOT NULL,
    "created_date" TIMESTAMP,
    "updated_date" TIMESTAMP,
    "admin_id" INTEGER NOT NULL
);

CREATE TABLE "cart" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_customer" INTEGER NOT NULL,
    "created_date" TIMESTAMP
);

CREATE TABLE "cart_item" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_cart" INTEGER NOT NULL,
    "id_product" INTEGER NOT NULL,
    "quantity" INTEGER NOT NULL,
    "created_date" TIMESTAMP
);

COMMIT;
